CREATE TABLE admin(
id BIGINT PRIMARY KEY ,
username VARCHAR(60) NOT NULL,
realname VARCHAR(60),
password_hash VARCHAR(60) NOT NULL,
created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)